/*
 * Content for the slot machine.
 * All three lists are plain arrays of strings — add, remove or reorder freely.
 * Everything here is user-facing, so the text is in Finnish.
 */

const DATA = {
  /* Reel 1 — passions. Replace with your own list. */
  passions: [
    "Juoksu",
    "Pyöräily",
    "Purjehdus",
    "Musiikki",
    "Tarinankerronta",
    "Stand-up komedia",
    "Visualisointi",
    "Kirjoittaminen",
    "Taide",
    "Eläinten kasvatus",
    "Kirjallisuus",
    "Sauna",
    "Hyvinkää",
    "Lempäälä",
    "Omakotitaloasuminen",
    "Tietokoneet",
    "Opettaminen",
    "Viini",
    "Elokuvat",
    "Videopelit",
    "Ohjelmointi",
    "Matkustaminen",
    "Muoti",
    "Arkkitehtuuri",
    "Ympäristönsuojelu",
    "Vanhemmuus",
    "Mielen hyvinvointi",
    "Kilpailuhenkisyys",
    "Juhliminen"
  ],

  /* Reel 2 — business sectors. 100 of them. */
  sectors: [
    "Rakentaminen",
    "Kiinteistönhuolto",
    "Kiinteistövälitys",
    "Asuminen ja vuokraus",
    "Arkkitehtuuri ja suunnittelu",
    "Ohjelmistokehitys",
    "Kyberturvallisuus",
    "Kommunikaatio ja viestintä",
    "Pelialan tuotanto",
    "Robotiikka",
    "Teollisuusautomaatio",
    "3D-tulostaminen",
    "Avaruusteollisuus",
    "Ilmailu",
    "Meriteollisuus",
    "Autoteollisuus",
    "Liikkuminen",
    "Logistiikka ja kuljetus",
    "Varastointi ja toimitusketjut",
    "Joukkoliikenne",
    "Kaupunkisuunnittelu",
    "Energiantuotanto",
    "Aurinko- ja tuulivoima",
    "Ydinvoima",
    "Sähköverkot ja energian varastointi",
    "Kaivosteollisuus",
    "Metsäteollisuus",
    "Puutuotteet ja rakennusmateriaalit",
    "Kiertotalous ja kierrätys",
    "Jätehuolto",
    "Vesihuolto",
    "Maatalous",
    "Kalastus ja vesiviljely",
    "Ravintolat ja kahvilat",
    "Baarit ja yöelämä",
    "Päivittäistavarakauppa",
    "Juomat ja panimot",
    "Terveydenhuolto",
    "Sairaalat ja klinikat",
    "Hammashoito",
    "Mielenterveys",
    "Ikääntyneiden hoiva",
    "Varhaiskasvatus",
    "Lääkinnälliset laitteet",
    "Kuntoutus ja fysioterapia",
    "Hyvinvointi ja kuntoilu",
    "Urheiluseurat ja -tapahtumat",
    "Ulkoilu ja retkeilyvarusteet",
    "Matkailu",
    "Hotellit ja majoitus",
    "Elämyspalvelut",
    "Tapahtumatuotanto",
    "Musiikkiala",
    "Elokuva ja televisio",
    "Media ja journalismi",
    "Kustantaminen ja kirjat",
    "Mainonta ja markkinointi",
    "Muotoilu ja brändit",
    "Muoti ja vaatetus",
    "Kauneus ja kosmetiikka",
    "Korut ja kellot",
    "Huonekalut ja sisustus",
    "Verkkokauppa",
    "Vähittäiskauppa",
    "Tukkukauppa",
    "Pankki ja rahoitus",
    "Vakuutus",
    "Sijoittaminen ja varainhoito",
    "Maksaminen ja fintech",
    "Kirjanpito ja tilintarkastus",
    "Juridiikka ja lakipalvelut",
    "Konsultointi",
    "Rekrytointi ja henkilöstöpalvelut",
    "Koulutus ja opetus",
    "Korkeakoulutus",
    "Ammatillinen täydennyskoulutus",
    "Kielet ja käännöspalvelut",
    "Museot ja kulttuuriperintö",
    "Taide ja galleriat",
    "Käsityö ja pientuotanto",
    "Lemmikit ja eläinlääkintä",
    "Siivous ja kotipalvelut",
    "Turvallisuusala ja vartiointi",
    "Puolustusteollisuus",
    "Julkishallinto",
    "Järjestöt ja hyväntekeväisyys",
    "B2B"
  ],

  /* Reel 3 — future scenarios. Written so they fit "maailmassa, jossa ___".
     Replace with your own list. */
  scenarios: [
    "energia on ilmaista",
    "äly ja tieto on kaikkien saatavilla",
    "täsmälääketiede on arkipäivää",
    "kuluttamisesta saa palkkaa",
    "ihmisillä on merkityspula",
    "massatyöttömyys on toteutunut",
    "ajattelutyöstä ei enää makseta",
    "ihmiset etsivät uusia yhteisöjä",
    "organisaatioiden hallinto on automatisoitua",
    "yksinäisyys on suurin kansanterveysongelma",
    "yksityisyyttä ei enää ole",
    "kansantalouden mittarit ovat muuttuneet",
    "työviikossa on kaksi päivää (korvaa nykyisen viikonlopun)",
    "työtehtävät asettaa tekoäly",
    "nykyiset korporaatiot ovat lopettaneet toimintansa",
    "kansainväliset rajat ovat poistuneet",
    "demokratia ei enää ehdi mukautumaan muutoksiin",
    "luottamuksen rakentaminen on ensisijaista",
    "kotitaloudet ovat omavaraisia",
    "perustulo on käytössä kaikkialla",

    // "ilmasto on lämmennyt neljä astetta",
    // "kaupungit ovat täysin autottomia",
    // "perustulo on käytössä kaikkialla",
    // "koulutus on ilmaista ja jatkuvaa",
    // "raha on täysin digitaalista",
    // "ruoka kasvatetaan kaupungeissa",
    // "sään hallinta on mahdollista",
    // "kaikki tavara on palvelu",
    // "3D-tulostus korvaa logistiikan",
    // "internet on kaatunut pysyvästi",
    // "ihmiset asuvat merellä",
    // "eläkeikä on poistunut",
    // "yksinäisyys on kansanterveysongelma numero yksi",
    // "geenimuokkaus on rutiinia",
    // "kaikki liikenne on autonomista",
    // "virtuaalimaailmoissa vietetään enemmän aikaa kuin fyysisessä"
  ]
};
