/*
 * Content for the slot machine.
 * All three lists are plain arrays of strings — add, remove or reorder freely.
 * Everything here is user-facing, so the text is in Finnish.
 */

const DATA = {
  /* Reel 1 — passions. Replace with your own list. */
  passions: [
    "Juoksu",
    "Pyöräily",
    "Hiihto",
    "Uinti",
    "Kiipeily",
    "Retkeily",
    "Metsästys",
    "Kalastus",
    "Purjehdus",
    "Sukellus",
    "Golf",
    "Jalkapallo",
    "Jääkiekko",
    "Kuntosali",
    "Jooga",
    "Tanssi",
    "Kokkaaminen",
    "Leipominen",
    "Kahvi",
    "Viini",
    "Puutarhanhoito",
    "Valokuvaus",
    "Elokuvat",
    "Musiikin tekeminen",
    "Vinyylit",
    "Lukeminen",
    "Kirjoittaminen",
    "Piirtäminen",
    "Keramiikka",
    "Puutyöt",
    "Vanhat autot",
    "Moottoripyörät",
    "Lautapelit",
    "Videopelit",
    "Ohjelmointi",
    "Elektroniikan rakentelu",
    "Astronomia",
    "Historia",
    "Matkustaminen",
    "Kielet",
    "Sauna",
    "Sienestys",
    "Linturetket",
    "Koirat",
    "Hevoset",
    "Meditaatio",
    "Sisustaminen",
    "Muoti",
    "Arkkitehtuuri",
    "Vapaaehtoistyö"
  ],

  /* Reel 2 — business sectors. 100 of them. */
  sectors: [
    "Rakentaminen",
    "Infrarakentaminen",
    "Kiinteistönhuolto",
    "Kiinteistövälitys",
    "Asuminen ja vuokraus",
    "Arkkitehtuuri ja suunnittelu",
    "Ohjelmistokehitys",
    "Tekoäly ja data",
    "Kyberturvallisuus",
    "Pilvipalvelut",
    "Datakeskukset",
    "Telekommunikaatio",
    "Pelialan tuotanto",
    "Robotiikka",
    "Teollisuusautomaatio",
    "Anturit ja mittaustekniikka",
    "Puolijohteet ja elektroniikka",
    "3D-tulostus ja lisäävä valmistus",
    "Konepajateollisuus",
    "Avaruusteollisuus",
    "Ilmailu",
    "Meriteollisuus",
    "Autoteollisuus",
    "Sähköinen liikkuminen",
    "Logistiikka ja kuljetus",
    "Varastointi ja toimitusketjut",
    "Joukkoliikenne",
    "Kaupunkisuunnittelu",
    "Energiantuotanto",
    "Aurinko- ja tuulivoima",
    "Ydinvoima",
    "Vetytalous",
    "Sähköverkot ja energian varastointi",
    "Kaivosteollisuus",
    "Metalliteollisuus",
    "Metsäteollisuus",
    "Puutuotteet ja rakennusmateriaalit",
    "Kemianteollisuus",
    "Materiaalitiede",
    "Kiertotalous ja kierrätys",
    "Jätehuolto",
    "Vesihuolto ja puhdistus",
    "Ympäristöteknologia",
    "Maatalous",
    "Elintarviketeollisuus",
    "Kalastus ja vesiviljely",
    "Ravintolat ja kahvilat",
    "Päivittäistavarakauppa",
    "Juomat ja panimot",
    "Terveydenhuolto",
    "Sairaalat ja klinikat",
    "Hammashoito",
    "Mielenterveys",
    "Ikääntyneiden hoiva",
    "Lastenhoito ja varhaiskasvatus",
    "Lääketeollisuus",
    "Biotekniikka",
    "Lääkinnälliset laitteet",
    "Kuntoutus ja fysioterapia",
    "Hyvinvointi ja kuntoilu",
    "Urheiluseurat ja -tapahtumat",
    "Ulkoilu ja retkeilyvarusteet",
    "Matkailu",
    "Hotellit ja majoitus",
    "Elämyspalvelut",
    "Tapahtumatuotanto",
    "Musiikkiala",
    "Elokuva ja televisio",
    "Media ja journalismi",
    "Kustantaminen ja kirjat",
    "Mainonta ja markkinointi",
    "Muotoilu ja brändit",
    "Muoti ja vaatetus",
    "Kauneus ja kosmetiikka",
    "Korut ja kellot",
    "Huonekalut ja sisustus",
    "Verkkokauppa",
    "Vähittäiskauppa",
    "Tukkukauppa",
    "Pankki ja rahoitus",
    "Vakuutus",
    "Sijoittaminen ja varainhoito",
    "Maksaminen ja fintech",
    "Lohkoketjut ja kryptovarat",
    "Kirjanpito ja tilintarkastus",
    "Juridiikka ja lakipalvelut",
    "Liikkeenjohdon konsultointi",
    "Rekrytointi ja henkilöstöpalvelut",
    "Koulutus ja opetus",
    "Korkeakoulutus",
    "Ammatillinen täydennyskoulutus",
    "Kielet ja käännöspalvelut",
    "Museot ja kulttuuriperintö",
    "Taide ja galleriat",
    "Käsityö ja pientuotanto",
    "Lemmikit ja eläinlääkintä",
    "Puutarha ja viherrakentaminen",
    "Siivous ja kotipalvelut",
    "Turvallisuusala ja vartiointi",
    "Puolustusteollisuus",
    "Julkishallinto",
    "Järjestöt ja hyväntekeväisyys"
  ],

  /* Reel 3 — future scenarios. Written so they fit "maailmassa, jossa ___".
     Replace with your own list. */
  scenarios: [
    "energia on ilmaista",
    "tekoäly tekee kaiken rutiinityön",
    "ihmiset elävät terveinä 120-vuotiaiksi",
    "kukaan ei omista autoa",
    "etätyö on täysin korvannut toimistot",
    "vesi on niukin luonnonvara",
    "robotit rakentavat talot",
    "kaikki materiaali kierrätetään ikuisesti",
    "liha valmistetaan laboratoriossa",
    "avaruusmatkailu on arkipäivää",
    "väestö vanhenee nopeammin kuin koskaan",
    "yksityisyyttä ei enää ole",
    "jokaisella on henkilökohtainen tekoälyagentti",
    "ilmasto on lämmennyt neljä astetta",
    "kaupungit ovat täysin autottomia",
    "perustulo on käytössä kaikkialla",
    "koulutus on ilmaista ja jatkuvaa",
    "raha on täysin digitaalista",
    "ruoka kasvatetaan kaupungeissa",
    "sään hallinta on mahdollista",
    "kaikki tavara on palvelu",
    "3D-tulostus korvaa logistiikan",
    "internet on kaatunut pysyvästi",
    "ihmiset asuvat merellä",
    "eläkeikä on poistunut",
    "yksinäisyys on kansanterveysongelma numero yksi",
    "geenimuokkaus on rutiinia",
    "kaikki liikenne on autonomista",
    "työviikko on kolme päivää",
    "virtuaalimaailmoissa vietetään enemmän aikaa kuin fyysisessä"
  ]
};
